#!/usr/bin/env python3
"""
Full line-follower stack for Puzzlebot.

Startup order:
  1. micro_ros_agent        — MCU serial bridge (UART → ROS 2)
  2. camera_raw_publisher   — CSI camera + lens undistortion → /camera/image_raw
  3. odometry_node          — wheel encoder integrator → /odom
  4. velocity_controller    — PI loop: /cmd_vel_desired → /cmd_vel → MCU
  5. twist_slew_limiter     — rate-limits /cmd_vel_desired_raw → /cmd_vel_desired
  6. line_follower_node     — image line detection + PD steering → /cmd_vel_desired_raw
  7. color_detector_node    — HSV traffic light detector (use_traffic=true)
  8. traffic_light_fsm_node — speed scale FSM driven by traffic light state (use_traffic=true)

Topic chain:
  line_follower_node → /cmd_vel_desired_raw
    → twist_slew_limiter → /cmd_vel_desired
    → velocity_controller → /cmd_vel → MCU

Usage:
    ros2 launch pzb_line_follower line_follower.launch.py
    ros2 launch pzb_line_follower line_follower.launch.py linear_speed:=0.12 Kp_angular:=0.004
    ros2 launch pzb_line_follower line_follower.launch.py use_traffic:=false
"""
import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration, PythonExpression
from launch_ros.actions import Node


def generate_launch_description():

    # ── Config file paths ─────────────────────────────────────────────────────
    lf_share      = get_package_share_directory('pzb_line_follower')
    cam_share     = get_package_share_directory('pzb_camera')
    ctrl_share    = get_package_share_directory('pzb_control')
    traffic_share = get_package_share_directory('pzb_traffic')

    lf_params      = os.path.join(lf_share,      'config', 'line_follower_params.yaml')
    cam_info       = os.path.join(cam_share,      'config', 'camera_info_8x5_3cm.yaml')
    ctrl_params    = os.path.join(ctrl_share,     'config', 'pid_vel_params.yaml')
    traffic_params = os.path.join(traffic_share,  'config', 'traffic_params.yaml')

    # Lens undistortion calibration — generated by cam_calibration.py (RMSE=0.31 px, 7×5 board)
    undistort_file = '/home/puzzlebot/streaming/camera_params.json'

    # ── Launch arguments ──────────────────────────────────────────────────────
    arg_linear_speed            = DeclareLaunchArgument('linear_speed',            default_value='0.06',  description='Forward speed (m/s). Lowered 0.08->0.06 (opt-bags turn fix): at 0.08 sharp turns outran the squashed-ROI look-ahead — the line swept off the edge before the robot rounded the bend (opt5/opt4 went out of bounds). Slower entry buys reaction frames and tightens the achievable radius (R=v/w, w capped). Following all 3 lines > speed.')
    arg_Kp_angular              = DeclareLaunchArgument('Kp_angular',              default_value='0.0045', description='Proportional steering gain (rad/s per px). Raised 0.0035->0.0045: medium curves (40-80px) were under-steered and the line drifted off.')
    arg_Kd_angular              = DeclareLaunchArgument('Kd_angular',              default_value='0.0',    description='Derivative steering gain (rad/s per px/frame); DISABLED (anti-stutter) — output EMA + error median do the damping')
    arg_dead_band_px            = DeclareLaunchArgument('dead_band_px',            default_value='12',    description='Pixel dead band for steering (widened for anti-stutter)')
    arg_publish_debug           = DeclareLaunchArgument('publish_debug',           default_value='false', description='Publish /camera/image_debug topic')
    arg_impl                    = DeclareLaunchArgument('impl',                    default_value='py',    description="Line-follower implementation: 'py' (pzb_line_follower) or 'cpp' (pzb_line_follower_cpp). C++ is a drop-in (same node name/topics/params) for lower Jetson CPU/memory.")
    arg_use_traffic             = DeclareLaunchArgument('use_traffic',             default_value='true',  description='Launch traffic light detector and FSM. It subscribes to the FULL-res /camera/image_raw (now raw/undistorted-off). It frame-skips (every 3rd frame) to limit CPU; if the Jetson is still tight, it can be repointed to /camera/image_small (it downscales its crop to 320x160 either way) or undistort re-enabled for it.')
    arg_undistort_enabled       = DeclareLaunchArgument('undistort_enabled',       default_value='true',  description='Apply lens undistortion to the small (line-follower) stream. Set false to A/B test the CPU saving (the follower is closed-loop and tolerates mild distortion).')
    arg_small_width             = DeclareLaunchArgument('small_width',             default_value='480',   description='Hardware-downscaled width for the line-follower stream (/camera/image_small)')
    arg_small_height            = DeclareLaunchArgument('small_height',            default_value='270',   description='Hardware-downscaled height for the line-follower stream (/camera/image_small)')
    arg_curve_speed_reduction   = DeclareLaunchArgument('curve_speed_reduction',   default_value='0.75',  description='Speed reduction on turns: 0=off, 1=stop at max angular')
    arg_min_linear_speed        = DeclareLaunchArgument('min_linear_speed',        default_value='0.05',  description='Floor linear speed (m/s) — keep above motor deadband')
    arg_max_linear_accel        = DeclareLaunchArgument('max_linear_accel',        default_value='5.0',   description='Max linear acceleration for slew limiter (m/s²)')
    arg_max_angular_accel       = DeclareLaunchArgument('max_angular_accel',       default_value='4.0',   description='Max angular acceleration for slew limiter (rad/s²). Raised 1.20->4.0: at 1.20 the downstream slew node needed ~0.47s (~3 cam frames @7fps) to ramp steering to 0.56 rad/s, so the robot left the mat before full steering reached the motors on sharp turns. 4.0 ramps in ~0.15s (~1 frame). Linear accel is left untouched (the brown-out concern is linear steps, not angular).')
    arg_sharp_turn_threshold_px = DeclareLaunchArgument('sharp_turn_threshold_px', default_value='60',    description='|error| px above which sharp-turn slow mode activates. Lowered 80->60 (opt-bags turn fix) so the hard curve-speed floor engages earlier, paired with the new error-driven early braking (curve_brake_error_px).')
    arg_sharp_turn_speed        = DeclareLaunchArgument('sharp_turn_speed',        default_value='0.03',  description='Linear speed (m/s) during sharp turns')
    arg_publish_compressed      = DeclareLaunchArgument('publish_compressed',      default_value='true',  description='Publish a JPEG /camera/image_compressed off the full frame for off-board YOLO (laptop GPU). Built from the same GStreamer full appsink — no extra camera handle. Only encodes when a subscriber is present, so it costs ~0 until YOLO connects. Default TRUE so YOLO has its feed without the heavy raw stream.')
    arg_jpeg_quality            = DeclareLaunchArgument('jpeg_quality',            default_value='75',    description='JPEG quality (1-100) for /camera/image_compressed')
    arg_publish_raw             = DeclareLaunchArgument('publish_raw',             default_value='false', description='Publish the FULL-res 2.76 MB /camera/image_raw Image. Default FALSE: this heavy publish + its DDS transport + bag recording back-pressured the GStreamer pipeline and froze the WHOLE graph for 1-18 s on the yolo bags (robot drove blind off curves). Off-board YOLO uses /camera/image_compressed instead, so raw is not needed on the robot. Set true only if a subscriber genuinely needs the uncompressed frame.')

    # ── 1. MCU bridge ─────────────────────────────────────────────────────────
    # Bridges the STM32 over UART to ROS 2 — publishes /wheel_speeds, subscribes /cmd_vel.
    # Comment out if running without hardware or when the MCU bridge is started separately.
    # node_mcu_bridge = Node(
    #     package='micro_ros_agent',
    #     executable='micro_ros_agent',
    #     name='micro_ros_agent',
    #     arguments=['serial', '-D', '/dev/ttyUSB0'],
    #     output='screen',
    # )

    # ── 2. Camera ─────────────────────────────────────────────────────────────
    # Opens the IMX219 CSI camera and publishes DUAL hardware-scaled streams (CPU fix):
    #   /camera/image_raw   — FULL 1280x720, raw (for off-board YOLO / recording)
    #   /camera/image_small — 480x270 hardware-downscaled (for the line follower)
    # Undistortion is applied only to the small stream (toggle: undistort_enabled).
    # Comment out when replaying a bag or using an external camera node.
    node_camera = Node(
        package='pzb_camera',
        executable='camera_raw_publisher',
        name='camera_raw_publisher',
        output='screen',
        parameters=[{
            'undistort_file':      undistort_file,
            'undistort_enabled':   LaunchConfiguration('undistort_enabled'),
            'small_width':         LaunchConfiguration('small_width'),
            'small_height':        LaunchConfiguration('small_height'),
            'camera_info_file':    cam_info,
            'publish_camera_info': True,
            'publish_compressed':  LaunchConfiguration('publish_compressed'),
            'jpeg_quality':        LaunchConfiguration('jpeg_quality'),
            'publish_raw':         LaunchConfiguration('publish_raw'),
        }],
    )

    # ── 3. Wheel odometry ─────────────────────────────────────────────────────
    # Integrates wheel encoder ticks from the MCU into /odom (nav_msgs/Odometry).
    # Comment out if odometry comes from another source (e.g. an EKF node).
    node_odometry = Node(
        package='pzb_control',
        executable='odometry_node',
        name='odometry_node',
        output='screen',
        parameters=[ctrl_params],
    )

    # ── 4. Velocity controller ────────────────────────────────────────────────
    # PI feedback loop that tracks /cmd_vel_desired and sends /cmd_vel to the MCU.
    # Comment out only when testing open-loop or bypassing closed-loop control.
    node_velocity_controller = Node(
        package='pzb_control',
        executable='velocity_controller',
        name='velocity_controller',
        output='screen',
        parameters=[ctrl_params],
    )

    # ── 5. Slew limiter ───────────────────────────────────────────────────────
    # Rate-limits acceleration between /cmd_vel_desired_raw → /cmd_vel_desired.
    # Prevents large velocity steps that cause MCU brown-out on the Jetson power rail.
    # Comment out only if the upstream planner already outputs smooth commands.
    node_slew_limiter = Node(
        package='pzb_utils',
        executable='twist_slew_limiter',
        name='twist_slew_limiter',
        output='screen',
        parameters=[{
            'input_topic':       '/cmd_vel_desired_raw',
            'output_topic':      '/cmd_vel_desired',
            'max_linear_accel':  LaunchConfiguration('max_linear_accel'),
            'max_angular_accel': LaunchConfiguration('max_angular_accel'),
            'max_linear_speed':  0.20,
            'max_angular_speed': 0.80,
        }],
    )

    # ── 6. Line follower ──────────────────────────────────────────────────────
    # Detects the line in /camera/image_raw and publishes steering + speed commands
    # to /cmd_vel_desired_raw, which the slew limiter forwards to /cmd_vel_desired.
    # Comment out to drive manually or with a different planner.
    # Select the Python or the C++ line follower (drop-in: identical node name, topics,
    # and parameters). impl:=cpp uses pzb_line_follower_cpp for lower Jetson CPU/memory.
    _lf_pkg = PythonExpression([
        "'pzb_line_follower_cpp' if '", LaunchConfiguration('impl'),
        "' == 'cpp' else 'pzb_line_follower'"])

    node_line_follower = Node(
        package=_lf_pkg,
        executable='line_follower_node',
        name='line_follower_node',
        output='screen',
        parameters=[
            lf_params,
            {
                'linear_speed':            LaunchConfiguration('linear_speed'),
                'Kp_angular':              LaunchConfiguration('Kp_angular'),
                'Kd_angular':              LaunchConfiguration('Kd_angular'),
                'dead_band_px':            LaunchConfiguration('dead_band_px'),
                'publish_debug':           LaunchConfiguration('publish_debug'),
                'curve_speed_reduction':   LaunchConfiguration('curve_speed_reduction'),
                'min_linear_speed':        LaunchConfiguration('min_linear_speed'),
                'sharp_turn_threshold_px': LaunchConfiguration('sharp_turn_threshold_px'),
                'sharp_turn_speed':        LaunchConfiguration('sharp_turn_speed'),
                'topic_cmd_vel':           '/cmd_vel_desired_raw',
                # Consume the hardware-downscaled stream (CPU fix) — the follower resizes
                # any input to its 320x80 ROI, and the uniform downscale preserves the
                # ROI anisotropy ratio (0.889), so no detector change is needed.
                'topic_image_in':          '/camera/image_small',
            },
        ],
    )

    # ── 7. Traffic light color detector ──────────────────────────────────────
    # HSV-based detector on /camera/image_raw, publishes /traffic_light_color.
    # Comment out (or pass use_traffic:=false) when running without traffic lights.
    node_color_detector = Node(
        package='pzb_traffic',
        executable='color_detector_node',
        name='color_detector_node',
        output='screen',
        condition=IfCondition(LaunchConfiguration('use_traffic')),
        parameters=[traffic_params],
    )

    # ── 8. Traffic light FSM ──────────────────────────────────────────────────
    # Subscribes to /traffic_light_color and outputs a speed scale on /traffic_speed_scale
    # that the line follower multiplies into its linear speed.
    # Comment out (or pass use_traffic:=false) together with node_color_detector above.
    node_traffic_fsm = Node(
        package='pzb_traffic',
        executable='traffic_light_fsm_node',
        name='traffic_light_fsm_node',
        output='screen',
        condition=IfCondition(LaunchConfiguration('use_traffic')),
        parameters=[traffic_params],
    )

    # ── Launch description ────────────────────────────────────────────────────
    return LaunchDescription([
        # arguments
        arg_linear_speed,
        arg_Kp_angular,
        arg_Kd_angular,
        arg_dead_band_px,
        arg_publish_debug,
        arg_impl,
        arg_use_traffic,
        arg_undistort_enabled,
        arg_small_width,
        arg_small_height,
        arg_curve_speed_reduction,
        arg_min_linear_speed,
        arg_max_linear_accel,
        arg_max_angular_accel,
        arg_sharp_turn_threshold_px,
        arg_sharp_turn_speed,
        arg_publish_compressed,
        arg_jpeg_quality,
        arg_publish_raw,

        # node_mcu_bridge,          # 1 — MCU serial bridge (commented: start separately)
        node_camera,                # 2 — CSI camera + lens undistortion → /camera/image_raw
        node_odometry,              # 3 — wheel encoder integrator → /odom
        node_velocity_controller,   # 4 — PI velocity loop → /cmd_vel → MCU
        node_slew_limiter,          # 5 — acceleration rate-limiter
        node_line_follower,         # 6 — line detection + PD steering → /cmd_vel_desired_raw
        node_color_detector,        # 7 — HSV traffic light detector (use_traffic=true)
        node_traffic_fsm,           # 8 — traffic light speed scale FSM (use_traffic=true)
    ])
